version: '3'

services:
  sensor-dashboard:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - sensor_data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000

volumes:
  sensor_data:
